src/Entity/Occasions.php
<?php

namespace App\Entity;

use App\Repository\OccasionsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OccasionsRepository::class)]
class Occasions
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $photo = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column]
    private ?float $price = null;

    #[ORM\Column(length: 4)]
    private ?string $miseCirculation = null;

    #[ORM\Column]
    private ?int $km = null;

    #[ORM\Column(length: 255)]
    private ?string $boite = null;

    #[ORM\Column(length: 255)]
    private ?string $energy = null;

    #[ORM\Column]
    private ?int $nbPortes = null;

    #[ORM\Column]
    private ?int $puissance = null;

    #[ORM\Column(length: 255)]
    private ?string $color = null;

    #[ORM\Column(length: 1)]
    private ?string $critair = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $post_date = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): static
    {
        $this->photo = $photo;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getMiseCirculation(): ?string
    {
        return $this->miseCirculation;
    }

    public function setMiseCirculation(string $miseCirculation): static
    {
        $this->miseCirculation = $miseCirculation;

        return $this;
    }

    public function getKm(): ?int
    {
        return $this->km;
    }

    public function setKm(int $km): static
    {
        $this->km = $km;

        return $this;
    }

    public function getBoite(): ?string
    {
        return $this->boite;
    }

    public function setBoite(string $boite): static
    {
        $this->boite = $boite;

        return $this;
    }

    public function getEnergy(): ?string
    {
        return $this->energy;
    }

    public function setEnergy(string $energy): static
    {
        $this->energy = $energy;

        return $this;
    }

    public function getNbPortes(): ?int
    {
        return $this->nbPortes;
    }

    public function setNbPortes(int $nbPortes): static
    {
        $this->nbPortes = $nbPortes;

        return $this;
    }

    public function getPuissance(): ?int
    {
        return $this->puissance;
    }

    public function setPuissance(int $puissance): static
    {
        $this->puissance = $puissance;

        return $this;
    }

    public function getColor(): ?string
    {
        return $this->color;
    }

    public function setColor(string $color): static
    {
        $this->color = $color;

        return $this;
    }

    public function getCritair(): ?string
    {
        return $this->critair;
    }

    public function setCritair(string $critair): static
    {
        $this->critair = $critair;

        return $this;
    }

    public function getPostDate(): ?\DateTimeInterface
    {
        return $this->post_date;
    }

    public function setPostDate(\DateTimeInterface $post_date): static
    {
        $this->post_date = $post_date;

        return $this;
    }
}

src/Controller/OccasionsController.php
<?php

namespace App\Controller;

use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Doctrine\ORM\EntityManagerInterface;
use App\Entity\Occasions;

class OccasionsController extends AbstractController
{
    #[Route('/occasions', name: 'app_occasions')]
    public function index(EntityManagerInterface $entityManager): Response
    {
        $occasions = $entityManager->getRepository(Occasions::class)->findBy(array(),array('post_date' => 'DESC', 'id' => 'DESC'));;
        return $this->render('occasions/index.html.twig', [
            'occasions' => $occasions,
            'controller_name' => 'OccasionsController',
        ]);
    }
}

templates/occasions/index.html.twig
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>{% block title %}Occasions | Garage Parrot{% endblock %}</title>
<link rel="icon" href="{{ asset('images/logo.png') }}">
{% block stylesheets %}
            {{ encore_entry_link_tags('occasions') }}
{% endblock %}

{% block javascripts %}
            {{ encore_entry_script_tags('occasions') }}
            
{% endblock %}
</head>
<body>
{% block body %}
    <header>
        <nav>
            <a href="/" class="logo"><img src="{{ asset('images/logo.png') }}" alt="Logo Garage Parrot"></a>
            <div class="nav-links">
                <ul>
                    <li><a href="/#offer">Services</a></li>
                    <li><a href="/occasions">Occasions</a></li>
                </ul>
            </div>
            {% if (is_granted('ROLE_ADMIN') or is_granted('ROLE_USER')) %}
                <a href="/account" class="cta">
                    <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="60" height="60" fill="currentColor" viewBox="0 0 24 24">
                        <path fill-rule="evenodd" d="M12 4a4 4 0 1 0 0 8 4 4 0 0 0 0-8Zm-2 9a4 4 0 0 0-4 4v1a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2v-1a4 4 0 0 0-4-4h-4Z" clip-rule="evenodd"/>
                    </svg>
                </a>
            {% else %}
                <a href="/login" class="cta">
                    <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="60" height="60" fill="currentColor" viewBox="0 0 24 24">
                        <path fill-rule="evenodd" d="M12 4a4 4 0 1 0 0 8 4 4 0 0 0 0-8Zm-2 9a4 4 0 0 0-4 4v1a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2v-1a4 4 0 0 0-4-4h-4Z" clip-rule="evenodd"/>
                    </svg>
                </a>
            {% endif %}

        </nav>
    </header>

    <section class="hero">
        <h2>Occasions</h2>
        <p>Consultez nos occasions pour trouver la voiture de vos rêves !</p>
    </section>

    <div class="occasions">
        {% for occasion in occasions %}
            <div class="card">
                <img src="{{ asset('images/occasions/' ~ occasion.photo) }}" class="bd-placeholder-img card-img-top" width="100%" height="225" alt="Image de {{ occasion.name }}">
                <div class="card-body">
                    <h3>{{ occasion.name }}</h3>
                    <p class="card-text">{{ occasion.description }}</p>
                    <section class="caracteristiques">
                        <p><svg xmlns="http://www.w3.org/2000/svg" width="34" height="34" fill="none" viewBox="0 0 24 24"><path fill="#e8eaed" d="M20.56 1C21.9 1 23 2.1 23 3.44v17.12C23 21.9 21.9 23 20.56 23H3.44A2.44 2.44 0 0 1 1 20.56V3.44C1 2.1 2.1 1 3.44 1zm0 7.33H3.44v12.23h17.12zM7.72 15.67a1.22 1.22 0 1 1 0 2.44H6.5a1.22 1.22 0 1 1 0-2.44zm4.9 0a1.22 1.22 0 0 1 .13 2.43l-.14.01H11.4a1.22 1.22 0 0 1-.14-2.44h1.36m-4.9-4.9a1.22 1.22 0 0 1 .14 2.44l-.14.01H6.5a1.22 1.22 0 0 1-.14-2.43l.14-.01zm4.9 0a1.22 1.22 0 0 1 0 2.45h-1.23a1.22 1.22 0 0 1 0-2.44zm4.88 0a1.22 1.22 0 0 1 .14 2.44l-.14.01h-1.22a1.22 1.22 0 0 1-.14-2.43l.14-.01zm3.06-7.33H3.44V5.9h17.12z"></path></svg>{{ occasion.miseCirculation }}</p>
                        <p><svg xmlns="http://www.w3.org/2000/svg" height="34" viewBox="0 -960 960 960" width="34" fill="#e8eaed"><path d="M480-80q-82 0-155-31.5t-127.5-86Q143-252 111.5-325T80-480q0-83 31.5-155.5t86-127Q252-817 325-848.5T480-880q83 0 155.5 31.5t127 86q54.5 54.5 86 127T880-480q0 82-31.5 155t-86 127.5q-54.5 54.5-127 86T480-80Zm0-240q60 0 117 17.5T704-252q46-46 71-104.5T800-480q0-134-93-227t-227-93q-134 0-227 93t-93 227q0 65 24.5 124T256-252q50-33 107-50.5T480-320Zm0 80q-41 0-80 10t-74 30q35 20 74 30t80 10q41 0 80-10t74-30q-35-20-74-30t-80-10ZM280-520q17 0 28.5-11.5T320-560q0-17-11.5-28.5T280-600q-17 0-28.5 11.5T240-560q0 17 11.5 28.5T280-520Zm120-120q17 0 28.5-11.5T440-680q0-17-11.5-28.5T400-720q-17 0-28.5 11.5T360-680q0 17 11.5 28.5T400-640Zm280 120q17 0 28.5-11.5T720-560q0-17-11.5-28.5T680-600q-17 0-28.5 11.5T640-560q0 17 11.5 28.5T680-520ZM480-400q33 0 56.5-23.5T560-480q0-13-4-25.5T544-528l54-136q7-16 .5-31.5T576-718q-15-7-30.5-.5T524-696l-54 136q-30 5-50 27.5T400-480q0 33 23.5 56.5T480-400Zm0 80Zm0-206Zm0 286Z"/></svg>{{ occasion.km }} km</p>
                        <p><svg xmlns="http://www.w3.org/2000/svg" width="34" height="34" fill="none" viewBox="0 0 24 24"><path fill="#e8eaed" d="M11.42 2.16a1.16 1.16 0 0 1 .14 2.3l-.14.01h-1.16v1.16h3.2q.45 0 .84.16l.2.09 3.75 1.87c.72.36 1.2 1.08 1.27 1.88v2.95h1.16v-1.16A1.16 1.16 0 0 1 23 11.3l.01.13v4.63a1.16 1.16 0 0 1-2.3.14l-.02-.14V14.9h-1.15v1.74c0 .66-.29 1.3-.78 1.73l-.15.12-3.86 2.9q-.52.39-1.18.45l-.2.01H3.31A2.3 2.3 0 0 1 1 19.7L1 19.53V7.95c0-1.22.94-2.22 2.14-2.31h4.81V4.46H6.79a1.16 1.16 0 0 1-.14-2.3l.14-.01zm2.04 5.79H3.32v11.58h10.03l3.86-2.9v-6.8zm-4.77 2.3a1.16 1.16 0 0 1 2.05 1.07l-.06.12-.69 1.14h1.41c.86 0 1.41.9 1.07 1.65l-.07.12-1.72 2.88a1.16 1.16 0 0 1-2.05-1.07l.06-.12.69-1.15H7.97c-.87 0-1.42-.89-1.07-1.65l.06-.12z"></path></svg>{{ occasion.energy }}</p>
                        <p><svg xmlns="http://www.w3.org/2000/svg" height="34" viewBox="0 -960 960 960" width="34" fill="#e8eaed"><path d="M160-120q-50 0-85-35t-35-85q0-39 22.5-70t57.5-43v-254q-35-12-57.5-43T40-720q0-50 35-85t85-35q50 0 85 35t35 85q0 39-22.5 70T200-607v87h240v-87q-35-12-57.5-43T360-720q0-50 35-85t85-35q50 0 85 35t35 85q0 39-22.5 70T520-607v87h200q17 0 28.5-11.5T760-560v-47q-35-12-57.5-43T680-720q0-50 35-85t85-35q50 0 85 35t35 85q0 39-22.5 70T840-607v47q0 50-35 85t-85 35H520v87q35 12 57.5 43t22.5 70q0 50-35 85t-85 35q-50 0-85-35t-35-85q0-39 22.5-70t57.5-43v-87H200v87q35 12 57.5 43t22.5 70q0 50-35 85t-85 35Zm0-80q17 0 28.5-11.5T200-240q0-17-11.5-28.5T160-280q-17 0-28.5 11.5T120-240q0 17 11.5 28.5T160-200Zm0-480q17 0 28.5-11.5T200-720q0-17-11.5-28.5T160-760q-17 0-28.5 11.5T120-720q0 17 11.5 28.5T160-680Zm320 480q17 0 28.5-11.5T520-240q0-17-11.5-28.5T480-280q-17 0-28.5 11.5T440-240q0 17 11.5 28.5T480-200Zm0-480q17 0 28.5-11.5T520-720q0-17-11.5-28.5T480-760q-17 0-28.5 11.5T440-720q0 17 11.5 28.5T480-680Zm320 0q17 0 28.5-11.5T840-720q0-17-11.5-28.5T800-760q-17 0-28.5 11.5T760-720q0 17 11.5 28.5T800-680ZM160-240Zm0-480Zm320 480Zm0-480Zm320 0Z"/></svg>{{ occasion.boite }}</p>
                        <p><svg xmlns="http://www.w3.org/2000/svg" width="34" height="34" fill="none" viewBox="0 0 24 24"><path fill="#e8eaed" d="M11.42 2.16a1.16 1.16 0 0 1 .14 2.3l-.14.01h-1.16v1.16h3.2q.45 0 .84.16l.2.09 3.75 1.87c.72.36 1.2 1.08 1.27 1.88v2.95h1.16v-1.16A1.16 1.16 0 0 1 23 11.3l.01.13v4.63a1.16 1.16 0 0 1-2.3.14l-.02-.14V14.9h-1.15v1.74c0 .66-.29 1.3-.78 1.73l-.15.12-3.86 2.9q-.52.39-1.18.45l-.2.01H3.31A2.3 2.3 0 0 1 1 19.7L1 19.53V7.95c0-1.22.94-2.22 2.14-2.31h4.81V4.46H6.79a1.16 1.16 0 0 1-.14-2.3l.14-.01zm2.04 5.79H3.32v11.58h10.03l3.86-2.9v-6.8z"></path></svg>{{ occasion.puissance }}ch</p>
                        <p><svg xmlns="http://www.w3.org/2000/svg" width="34" height="34" fill="none" viewBox="0 0 24 24"><path fill="#e8eaed" d="M15.67 14.44a1.22 1.22 0 1 0 0 2.45h1.22a1.22 1.22 0 0 0 0-2.45z"></path><path fill="#e8eaed" fill-rule="evenodd" d="M6.38 4.42A8.6 8.6 0 0 1 13.22 1h6.11A3.67 3.67 0 0 1 23 4.67v15.89C23 21.9 21.9 23 20.56 23H3.44A2.44 2.44 0 0 1 1 20.56v-6.93c0-1.32.43-2.6 1.22-3.67zm6.84-.98c-1.92 0-3.73.91-4.89 2.45l-3.66 4.89h15.89V4.67c0-.68-.55-1.23-1.23-1.23zM3.44 13.63q0-.2.03-.4h17.09v7.33H3.44z" clip-rule="evenodd"></path></svg>{{ occasion.nbPortes }} portes</p>
                        <p><svg xmlns="http://www.w3.org/2000/svg" width="34" height="34" fill="none" viewBox="0 0 24 24"><path fill="#e8eaed" d="M12 23C5.94 23 1 18.06 1 12S5.94 1 12 1s11 4.94 11 11-4.94 11-11 11m0-20.67a9.69 9.69 0 0 0 0 19.34 9.69 9.69 0 0 0 0-19.34"></path><path fill="#e8eaed" d="M10.03 7.8c1.5-.05 2.81.55 4.04 1.32q1.7 1.05 3.3 2.24.61.46.98 1.14c.46.9.11 1.9-.83 2.4q-.7.28-1.45.48a.5.5 0 0 0-.22.16 1.46 1.46 0 0 1-1.81.54q-.32-.14-.54-.41a.6.6 0 0 0-.39-.2h-2.99q-.17 0-.3.13c-.51.6-1.07.73-1.77.39a1.35 1.35 0 0 1-.67-1.4A1.4 1.4 0 0 1 8.6 13.5a1.3 1.3 0 0 1 1.26.6.4.4 0 0 0 .23.15q1.56 0 3.11-.03a.3.3 0 0 0 .22-.13 1.48 1.48 0 0 1 2.22-.2c.35.36.67.4 1.1.15.69-.4.68-1.06-.07-1.53-.54-.33-1.16-.56-1.7-.91-.74-.48-1.43-1.03-2.13-1.56a5 5 0 0 0-3.13-1.13 3.3 3.3 0 0 0-2.8 2.01c-.31.79-.2 1.54-.01 2.32q.12.59.15 1.2a.6.6 0 0 1-.2.39c-.04.03-.28-.06-.34-.15q-.46-.65-.8-1.39a3.2 3.2 0 0 1-.13-2.16c.36-1.14.93-2.14 2.07-2.75a5 5 0 0 1 2.38-.58"></path></svg>Crit'Air {{ occasion.critair }}</p>
                        {% if (occasion.postDate|date('U') > (date('now')|date_modify('-4 days')|date('U'))) %}
                            <p><svg xmlns="http://www.w3.org/2000/svg" width="34" height="34" fill="none" viewBox="0 0 24 24"><g fill="#e8eaed" clip-path="url(#a)"><path d="M8.9 22.52q-.15 0-.3-.05a1 1 0 0 1-.55-.5l-.9-1.87c-.25-.54-.75-.9-1.34-.98l-2.06-.25a.94.94 0 0 1-.8-1.11l.37-2.05a1.7 1.7 0 0 0-.5-1.58L1.3 12.71a.96.96 0 0 1 0-1.4L2.8 9.87c.43-.4.62-.98.5-1.56l-.38-2.04a.94.94 0 0 1 .8-1.11l2.07-.27a1.7 1.7 0 0 0 1.34-.98l.89-1.87a1 1 0 0 1 .56-.5 1 1 0 0 1 .75.07l2 1.09c.4.22.9.22 1.3 0l2.01-1.1q.36-.18.75-.08a1 1 0 0 1 .56.5l.9 1.88c.25.54.75.9 1.34.97l2.06.26a.94.94 0 0 1 .8 1.1l-.38 2.07c-.1.58.08 1.16.5 1.56l1.53 1.43q.29.28.29.69c0 .25-.1.51-.3.7L21.2 14.1c-.43.41-.62.99-.5 1.57l.38 2.04a.94.94 0 0 1-.8 1.11l-2.07.26c-.59.08-1.1.45-1.35.98l-.88 1.88a1 1 0 0 1-.56.5 1 1 0 0 1-.75-.07l-2.01-1.1c-.4-.22-.9-.22-1.3 0l-2 1.1a1 1 0 0 1-.46.11zm-4.8-4.76 1.85.23c.98.13 1.81.73 2.23 1.63l.8 1.7 1.83-1.01c.73-.4 1.66-.4 2.39 0l1.83 1 .8-1.69c.42-.89 1.25-1.5 2.23-1.62l1.87-.23-.35-1.85c-.18-.95.13-1.93.84-2.6l1.38-1.3-1.37-1.28a2.9 2.9 0 0 1-.85-2.61l.35-1.86-1.85-.24a2.8 2.8 0 0 1-2.23-1.62l-.8-1.7-1.83 1c-.73.4-1.66.4-2.4 0l-1.81-1-.8 1.7a2.9 2.9 0 0 1-2.22 1.62l-1.87.24.35 1.84c.18.96-.13 1.93-.84 2.6l-1.38 1.3 1.37 1.29c.71.67 1.03 1.65.85 2.62l-.35 1.85z"></path><path d="M9.65 13.97H8.6l-1.72-2.98h-.02q.05.78.05 1.13v1.85h-.75v-3.94H7.2l1.71 2.95h.02q-.04-.76-.04-1.08v-1.86h.75zM12.9 13.97h-2.26v-3.94h2.27v.69h-1.44v.86h1.33v.68h-1.33v1.02h1.44zM17.56 13.97h-.94l-.54-2.07-.19-.92q0 .15-.08.47l-.1.45-.53 2.06h-.95l-1-3.94h.82l.5 2.15q.14.6.2 1.03 0-.15.07-.47.06-.33.12-.5l.57-2.2h.78l.57 2.2.1.45.08.52a12 12 0 0 1 .2-1.02l.5-2.15h.82z"></path></g><defs><clipPath id="a"><path fill="#fff" d="M0 0h24v24H0z"></path></clipPath></defs></svg>Annonce récente</p>
                        {% endif %}
                    </section>
                    <p class="price">{{ occasion.price }} €</p>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}
</body>
</html>